### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by Iazzetta** [erycson/BloodStrike#3]
Hey Erycson, I pull this project and start maven. But when I join in the page, the game don't start. 

`[DEBUG] 2017-03-06 15:22:51.370 [vert.x-eventloop-thread-1] PacketHandler - Pacote recebido: syncServerTime
[DEBUG] 2017-03-06 15:22:51.372 [vert.x-eventloop-thread-1] PacketHandler - Pacote recebido: login
java.nio.file.NoSuchFileException: D:\callBackLoginSuccess2.dump
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.bloodstrike.lobbyserver.packet.client.PROTOCOL_BASE_LOGIN_REQ.run(PROTOCOL_BASE_LOGIN_REQ.java:82)
	at com.bloodstrike.lobbyserver.packet.PacketHandler.handle(PacketHandler.java:54)
	at com.bloodstrike.lobbyserver.ConnetionHandler.handle(ConnetionHandler.java:50)
	at com.bloodstrike.lobbyserver.ConnetionHandler.handle(ConnetionHandler.java:25)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:312)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:67)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:67)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)`

Appears a black screen written "carregado ..."
Can you help me? Thanks!

**Comment by erycson** [comment]
Sorry, but for the reason of the login package I gave a break in the development. This error happens because I was sending a file (callBackLoginSuccess2.dump) as a response since I could not rewrite the login package.

File: src/main/java/com/bloodstrike/lobbyserver/packet/client/PROTOCOL_BASE_LOGIN_REQ.java
Line: 82

**Comment by LapisBlock** [comment]
I Will Help you, first send me your jar and i help you
